apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
  labels:
    deploymentName: kafka-python-consumer
spec:
  scaleTargetRef:
    name: kafka-python-consumer
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: 192.168.41.165:9092
        consumerGroup: group1
        topic: data-json
        # Optional
        lagThreshold: "50"
        offsetResetPolicy: latest